version: '3.9'

services:
  server:
    build: .
  db:
    image: postgres:10-alpine
    restart: unless-stopped
    ports:
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
